/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProceduresRouteImport } from './routes/procedures'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProceduresProcedureIdRouteImport } from './routes/procedures.$procedureId'

const ProceduresRoute = ProceduresRouteImport.update({
  id: '/procedures',
  path: '/procedures',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProceduresProcedureIdRoute = ProceduresProcedureIdRouteImport.update({
  id: '/$procedureId',
  path: '/$procedureId',
  getParentRoute: () => ProceduresRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/procedures': typeof ProceduresRouteWithChildren
  '/procedures/$procedureId': typeof ProceduresProcedureIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/procedures': typeof ProceduresRouteWithChildren
  '/procedures/$procedureId': typeof ProceduresProcedureIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/procedures': typeof ProceduresRouteWithChildren
  '/procedures/$procedureId': typeof ProceduresProcedureIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/procedures' | '/procedures/$procedureId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/procedures' | '/procedures/$procedureId'
  id: '__root__' | '/' | '/procedures' | '/procedures/$procedureId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProceduresRoute: typeof ProceduresRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/procedures': {
      id: '/procedures'
      path: '/procedures'
      fullPath: '/procedures'
      preLoaderRoute: typeof ProceduresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procedures/$procedureId': {
      id: '/procedures/$procedureId'
      path: '/$procedureId'
      fullPath: '/procedures/$procedureId'
      preLoaderRoute: typeof ProceduresProcedureIdRouteImport
      parentRoute: typeof ProceduresRoute
    }
  }
}

interface ProceduresRouteChildren {
  ProceduresProcedureIdRoute: typeof ProceduresProcedureIdRoute
}

const ProceduresRouteChildren: ProceduresRouteChildren = {
  ProceduresProcedureIdRoute: ProceduresProcedureIdRoute,
}

const ProceduresRouteWithChildren = ProceduresRoute._addFileChildren(
  ProceduresRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProceduresRoute: ProceduresRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
