/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProceduresRouteImport } from './routes/procedures'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffSelectRouteImport } from './routes/staff.select'
import { Route as StaffLoginRouteImport } from './routes/staff.login'
import { Route as ProceduresProcedureIdRouteImport } from './routes/procedures.$procedureId'

const ProceduresRoute = ProceduresRouteImport.update({
  id: '/procedures',
  path: '/procedures',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffSelectRoute = StaffSelectRouteImport.update({
  id: '/staff/select',
  path: '/staff/select',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff/login',
  path: '/staff/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProceduresProcedureIdRoute = ProceduresProcedureIdRouteImport.update({
  id: '/$procedureId',
  path: '/$procedureId',
  getParentRoute: () => ProceduresRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/journey': typeof JourneyRoute
  '/procedures': typeof ProceduresRouteWithChildren
  '/procedures/$procedureId': typeof ProceduresProcedureIdRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/select': typeof StaffSelectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/journey': typeof JourneyRoute
  '/procedures': typeof ProceduresRouteWithChildren
  '/procedures/$procedureId': typeof ProceduresProcedureIdRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/select': typeof StaffSelectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/journey': typeof JourneyRoute
  '/procedures': typeof ProceduresRouteWithChildren
  '/procedures/$procedureId': typeof ProceduresProcedureIdRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/select': typeof StaffSelectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/journey'
    | '/procedures'
    | '/procedures/$procedureId'
    | '/staff/login'
    | '/staff/select'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/journey'
    | '/procedures'
    | '/procedures/$procedureId'
    | '/staff/login'
    | '/staff/select'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/journey'
    | '/procedures'
    | '/procedures/$procedureId'
    | '/staff/login'
    | '/staff/select'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  JourneyRoute: typeof JourneyRoute
  ProceduresRoute: typeof ProceduresRouteWithChildren
  StaffLoginRoute: typeof StaffLoginRoute
  StaffSelectRoute: typeof StaffSelectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/procedures': {
      id: '/procedures'
      path: '/procedures'
      fullPath: '/procedures'
      preLoaderRoute: typeof ProceduresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/select': {
      id: '/staff/select'
      path: '/staff/select'
      fullPath: '/staff/select'
      preLoaderRoute: typeof StaffSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/login': {
      id: '/staff/login'
      path: '/staff/login'
      fullPath: '/staff/login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procedures/$procedureId': {
      id: '/procedures/$procedureId'
      path: '/$procedureId'
      fullPath: '/procedures/$procedureId'
      preLoaderRoute: typeof ProceduresProcedureIdRouteImport
      parentRoute: typeof ProceduresRoute
    }
  }
}

interface ProceduresRouteChildren {
  ProceduresProcedureIdRoute: typeof ProceduresProcedureIdRoute
}

const ProceduresRouteChildren: ProceduresRouteChildren = {
  ProceduresProcedureIdRoute: ProceduresProcedureIdRoute,
}

const ProceduresRouteWithChildren = ProceduresRoute._addFileChildren(
  ProceduresRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  JourneyRoute: JourneyRoute,
  ProceduresRoute: ProceduresRouteWithChildren,
  StaffLoginRoute: StaffLoginRoute,
  StaffSelectRoute: StaffSelectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
